# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, qrc

class Ui_list(object):
    def setupUi(self, list):
        list.setObjectName("list")
        list.resize(1500, 750)
        list.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        list.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.gridLayout = QtWidgets.QGridLayout(list)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(list)
        self.widget.setObjectName("widget")
        self.listbackground = QtWidgets.QLabel(self.widget)
        self.listbackground.setGeometry(QtCore.QRect(4, 6, 1475, 725))
        self.listbackground.setStyleSheet("border-image: url(:/img/img/cover.jpg);\n"
"border-radius: 20px;")
        self.listbackground.setText("")
        self.listbackground.setObjectName("listbackground")
        self.listcroix = QtWidgets.QToolButton(self.widget)
        self.listcroix.setGeometry(QtCore.QRect(1415, 30, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listcroix.setFont(font)
        self.listcroix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listcroix.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.listcroix.setObjectName("listcroix")
        self.listpetit = QtWidgets.QToolButton(self.widget)
        self.listpetit.setGeometry(QtCore.QRect(1365, 30, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.listpetit.setFont(font)
        self.listpetit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listpetit.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.listpetit.setObjectName("listpetit")
        self.listtitre = QtWidgets.QLabel(self.widget)
        self.listtitre.setGeometry(QtCore.QRect(550, 30, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.listtitre.setFont(font)
        self.listtitre.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listtitre.setAlignment(QtCore.Qt.AlignCenter)
        self.listtitre.setObjectName("listtitre")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 120, 1390, 481))
        self.scrollArea.setStyleSheet("background: rgba(255, 255, 255, 0;)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1388, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listtask = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listtask.setFont(font)
        self.listtask.setStyleSheet("background: rgba(255, 255, 255, .33);\n"
"border: 2px solid;")
        self.listtask.setObjectName("listtask")
        self.listnomtodolist = QtWidgets.QLabel(self.listtask)
        self.listnomtodolist.setGeometry(QtCore.QRect(10, 10, 500, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listnomtodolist.setFont(font)
        self.listnomtodolist.setStyleSheet("border: 0px solid;\n"
"background: none;\n"
"")
        self.listnomtodolist.setObjectName("listnomtodolist")
        self.listdescription = QtWidgets.QLabel(self.listtask)
        self.listdescription.setGeometry(QtCore.QRect(10, 60, 500, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listdescription.setFont(font)
        self.listdescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.listdescription.setObjectName("listdescription")
        self.listline = QtWidgets.QFrame(self.listtask)
        self.listline.setGeometry(QtCore.QRect(660, 50, 3, 61))
        self.listline.setFrameShape(QtWidgets.QFrame.VLine)
        self.listline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listline.setObjectName("listline")
        self.listtaskrest = QtWidgets.QLabel(self.listtask)
        self.listtaskrest.setGeometry(QtCore.QRect(580, 60, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.listtaskrest.setFont(font)
        self.listtaskrest.setStyleSheet("border: 0px solid;\n"
"")
        self.listtaskrest.setAlignment(QtCore.Qt.AlignCenter)
        self.listtaskrest.setObjectName("listtaskrest")
        self.listtaskfait = QtWidgets.QLabel(self.listtask)
        self.listtaskfait.setGeometry(QtCore.QRect(680, 60, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.listtaskfait.setFont(font)
        self.listtaskfait.setStyleSheet("border: 0px solid;")
        self.listtaskfait.setAlignment(QtCore.Qt.AlignCenter)
        self.listtaskfait.setObjectName("listtaskfait")
        self.listpoubelleicon = QtWidgets.QLabel(self.listtask)
        self.listpoubelleicon.setGeometry(QtCore.QRect(820, 40, 70, 70))
        self.listpoubelleicon.setStyleSheet("border: 0px solid;\n"
"background-color: rgba(0,0,0,0);\n"
"image: url(:/img/img/trash_bin_icon-icons.com_67981.png);")
        self.listpoubelleicon.setText("")
        self.listpoubelleicon.setObjectName("listpoubelleicon")
        self.listmodifiericon = QtWidgets.QLabel(self.listtask)
        self.listmodifiericon.setGeometry(QtCore.QRect(960, 40, 70, 70))
        self.listmodifiericon.setStyleSheet("border: 0px solid;\n"
"background-color: rgba(0,0,0,0);\n"
"image: url(:/img/img/edit_icon_128873.png);")
        self.listmodifiericon.setText("")
        self.listmodifiericon.setObjectName("listmodifiericon")
        self.listinfoicon = QtWidgets.QLabel(self.listtask)
        self.listinfoicon.setGeometry(QtCore.QRect(1100, 40, 70, 70))
        self.listinfoicon.setStyleSheet("border: 0px solid;\n"
"background-color: rgba(0,0,0,0);\n"
"image: url(:/img/img/apps_list_detail_regular_icon_205678.png);")
        self.listinfoicon.setText("")
        self.listinfoicon.setObjectName("listinfoicon")
        self.listdlicon = QtWidgets.QLabel(self.listtask)
        self.listdlicon.setGeometry(QtCore.QRect(1240, 40, 70, 70))
        self.listdlicon.setStyleSheet("border: 0px solid;\n"
"background-color: rgba(0,0,0,0);\n"
"image: url(:/img/img/import_download_icon_143002.png);")
        self.listdlicon.setText("")
        self.listdlicon.setObjectName("listdlicon")
        self.listajoutertodolist_2 = QtWidgets.QToolButton(self.listtask)
        self.listajoutertodolist_2.setGeometry(QtCore.QRect(780, 20, 151, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.listajoutertodolist_2.setFont(font)
        self.listajoutertodolist_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listajoutertodolist_2.setAutoFillBackground(False)
        self.listajoutertodolist_2.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listajoutertodolist_2.setText("")
        self.listajoutertodolist_2.setCheckable(False)
        self.listajoutertodolist_2.setAutoExclusive(False)
        self.listajoutertodolist_2.setAutoRepeatInterval(100)
        self.listajoutertodolist_2.setObjectName("listajoutertodolist_2")
        self.gridLayout_3.addWidget(self.listtask, 1, 0, 1, 1)
        self.gridLayout_3.setRowMinimumHeight(1, 150)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.listboutondeco = QtWidgets.QToolButton(self.widget)
        self.listboutondeco.setGeometry(QtCore.QRect(1270, 630, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listboutondeco.setFont(font)
        self.listboutondeco.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listboutondeco.setAutoFillBackground(False)
        self.listboutondeco.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listboutondeco.setCheckable(False)
        self.listboutondeco.setAutoExclusive(False)
        self.listboutondeco.setAutoRepeatInterval(100)
        self.listboutondeco.setObjectName("listboutondeco")
        self.listajoutertodolist = QtWidgets.QToolButton(self.widget)
        self.listajoutertodolist.setGeometry(QtCore.QRect(600, 620, 300, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.listajoutertodolist.setFont(font)
        self.listajoutertodolist.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listajoutertodolist.setAutoFillBackground(False)
        self.listajoutertodolist.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listajoutertodolist.setCheckable(False)
        self.listajoutertodolist.setAutoExclusive(False)
        self.listajoutertodolist.setAutoRepeatInterval(100)
        self.listajoutertodolist.setObjectName("listajoutertodolist")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(list)
        QtCore.QMetaObject.connectSlotsByName(list)

    def retranslateUi(self, list):
        _translate = QtCore.QCoreApplication.translate
        list.setWindowTitle(_translate("list", "Dialog"))
        self.listcroix.setText(_translate("list", "X"))
        self.listpetit.setText(_translate("list", "-"))
        self.listtitre.setText(_translate("list", "Bienvenue (nom + prenom)"))
        self.listnomtodolist.setText(_translate("list", "Nom to do list"))
        self.listdescription.setText(_translate("list", "Description"))
        self.listtaskrest.setText(_translate("list", "0"))
        self.listtaskfait.setText(_translate("list", "0"))
        self.listboutondeco.setText(_translate("list", "Déconnexion"))
        self.listajoutertodolist.setText(_translate("list", "Ajouter une To Do List"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Login = QtWidgets.QWidget()
        ui = Ui_list()
        ui.setupUi(Login)
        Login.show()
        sys.exit(app.exec_())
