# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addtask.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, qrc


class Ui_addtask(object):
    def setupUi(self, addtask):
        addtask.setObjectName("addtask")
        addtask.setEnabled(True)
        addtask.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        addtask.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        addtask.resize(700, 900)
        self.addtaskmainwidget = QtWidgets.QWidget(addtask)
        self.addtaskmainwidget.setGeometry(QtCore.QRect(25, 25, 650, 850))
        self.addtaskmainwidget.setObjectName("addtaskmainwidget")
        self.addtaskimgback = QtWidgets.QLabel(self.addtaskmainwidget)
        self.addtaskimgback.setGeometry(QtCore.QRect(0, 0, 650, 850))
        self.addtaskimgback.setStyleSheet("border-image: url(:/img/img/cover.jpg);\n"
"border-radius: 20px;")
        self.addtaskimgback.setText("")
        self.addtaskimgback.setObjectName("addtaskimgback")
        self.addtasktitre = QtWidgets.QLabel(self.addtaskmainwidget)
        self.addtasktitre.setGeometry(QtCore.QRect(125, 75, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.addtasktitre.setFont(font)
        self.addtasktitre.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.addtasktitre.setAlignment(QtCore.Qt.AlignCenter)
        self.addtasktitre.setObjectName("addtasktitre")
        self.addtasknomuser = QtWidgets.QLineEdit(self.addtaskmainwidget)
        self.addtasknomuser.setGeometry(QtCore.QRect(75, 200, 500, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addtasknomuser.sizePolicy().hasHeightForWidth())
        self.addtasknomuser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.addtasknomuser.setFont(font)
        self.addtasknomuser.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.addtasknomuser.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.addtasknomuser.setAcceptDrops(True)
        self.addtasknomuser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addtasknomuser.setAutoFillBackground(False)
        self.addtasknomuser.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.addtasknomuser.setText("")
        self.addtasknomuser.setCursorPosition(0)
        self.addtasknomuser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.addtasknomuser.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.addtasknomuser.setObjectName("addtasknomuser")
        self.addtaskboutoncon = QtWidgets.QToolButton(self.addtaskmainwidget)
        self.addtaskboutoncon.setGeometry(QtCore.QRect(200, 750, 250, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addtaskboutoncon.setFont(font)
        self.addtaskboutoncon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addtaskboutoncon.setAutoFillBackground(False)
        self.addtaskboutoncon.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.addtaskboutoncon.setCheckable(False)
        self.addtaskboutoncon.setAutoExclusive(False)
        self.addtaskboutoncon.setAutoRepeatInterval(100)
        self.addtaskboutoncon.setObjectName("addtaskboutoncon")
        self.addtaskcroix = QtWidgets.QToolButton(self.addtaskmainwidget)
        self.addtaskcroix.setGeometry(QtCore.QRect(590, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addtaskcroix.setFont(font)
        self.addtaskcroix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addtaskcroix.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.addtaskcroix.setObjectName("addtaskcroix")
        self.addtaskpetit = QtWidgets.QToolButton(self.addtaskmainwidget)
        self.addtaskpetit.setGeometry(QtCore.QRect(540, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.addtaskpetit.setFont(font)
        self.addtaskpetit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addtaskpetit.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.addtaskpetit.setObjectName("addtaskpetit")
        self.addtaskfondnoir = QtWidgets.QLabel(self.addtaskmainwidget)
        self.addtaskfondnoir.setGeometry(QtCore.QRect(25, 175, 600, 550))
        self.addtaskfondnoir.setStyleSheet("background: rgba(0, 0, 0, .33);\n"
"border-radius: 30px;")
        self.addtaskfondnoir.setText("")
        self.addtaskfondnoir.setObjectName("addtaskfondnoir")
        self.addtaskwidgscroll = QtWidgets.QWidget(self.addtaskmainwidget)
        self.addtaskwidgscroll.setGeometry(QtCore.QRect(60, 500, 525, 200))
        self.addtaskwidgscroll.setObjectName("addtaskwidgscroll")
        self.gridLayout = QtWidgets.QGridLayout(self.addtaskwidgscroll)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.addtaskcrollArea = QtWidgets.QScrollArea(self.addtaskwidgscroll)
        self.addtaskcrollArea.setStyleSheet("background: rgb(255, 255, 255, 0;);\n"
"border-radius: 0px;")
        self.addtaskcrollArea.setWidgetResizable(True)
        self.addtaskcrollArea.setObjectName("addtaskcrollArea")
        self.addtaskscrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.addtaskscrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 505, 180))
        self.addtaskscrollAreaWidgetContents_2.setObjectName("addtaskscrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.addtaskscrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addtaskcheckBox = QtWidgets.QCheckBox(self.addtaskscrollAreaWidgetContents_2)
        self.addtaskcheckBox.setStyleSheet(" height: 32px;")
        self.addtaskcheckBox.setText("")
        self.addtaskcheckBox.setObjectName("addtaskcheckBox")
        self.gridLayout_2.addWidget(self.addtaskcheckBox, 4, 0, 1, 1)
        self.addtasknom = QtWidgets.QLabel(self.addtaskscrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addtasknom.setFont(font)
        self.addtasknom.setStyleSheet("color: rgba(255, 255, 255, .60;);")
        self.addtasknom.setObjectName("addtasknom")
        self.gridLayout_2.addWidget(self.addtasknom, 4, 1, 1, 1)
        self.addtaskcheckBox_2 = QtWidgets.QCheckBox(self.addtaskscrollAreaWidgetContents_2)
        self.addtaskcheckBox_2.setStyleSheet(" height: 32px;")
        self.addtaskcheckBox_2.setText("")
        self.addtaskcheckBox_2.setIconSize(QtCore.QSize(16, 16))
        self.addtaskcheckBox_2.setObjectName("addtaskcheckBox_2")
        self.gridLayout_2.addWidget(self.addtaskcheckBox_2, 3, 0, 1, 1)
        self.addtasknom_2 = QtWidgets.QLabel(self.addtaskscrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addtasknom_2.setFont(font)
        self.addtasknom_2.setStyleSheet("color: rgba(255, 255, 255, .60;);")
        self.addtasknom_2.setObjectName("addtasknom_2")
        self.gridLayout_2.addWidget(self.addtasknom_2, 3, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.addtaskcrollArea.setWidget(self.addtaskscrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.addtaskcrollArea, 0, 0, 1, 1)
        self.addtaskprio = QtWidgets.QComboBox(self.addtaskmainwidget)
        self.addtaskprio.setGeometry(QtCore.QRect(75, 275, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addtaskprio.setFont(font)
        self.addtaskprio.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, .60;);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.addtaskprio.setObjectName("addtaskprio")
        self.addtaskprio.addItem("")
        self.addtaskprio.addItem("")
        self.addtaskprio.addItem("")
        self.addtaskprio.addItem("")
        self.addtasktime = QtWidgets.QDateTimeEdit(self.addtaskmainwidget)
        self.addtasktime.setGeometry(QtCore.QRect(75, 350, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addtasktime.setFont(font)
        self.addtasktime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addtasktime.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, .60;);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.addtasktime.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.addtasktime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.addtasktime.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.addtasktime.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.addtasktime.setTimeSpec(QtCore.Qt.LocalTime)
        self.addtasktime.setObjectName("addtasktime")
        self.addtasketiquette = QtWidgets.QComboBox(self.addtaskmainwidget)
        self.addtasketiquette.setGeometry(QtCore.QRect(75, 425, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addtasketiquette.setFont(font)
        self.addtasketiquette.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, .60;);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.addtasketiquette.setObjectName("addtasketiquette")
        self.addtasketiquette.addItem("")
        self.addtasketiquette.addItem("")
        self.addtasketiquette.addItem("")
        self.addtasketiquette.addItem("")
        self.addtaskimgback.raise_()
        self.addtasktitre.raise_()
        self.addtaskcroix.raise_()
        self.addtaskpetit.raise_()
        self.addtaskboutoncon.raise_()
        self.addtaskfondnoir.raise_()
        self.addtasknomuser.raise_()
        self.addtaskwidgscroll.raise_()
        self.addtaskprio.raise_()
        self.addtasktime.raise_()
        self.addtasketiquette.raise_()

        self.retranslateUi(addtask)
        QtCore.QMetaObject.connectSlotsByName(addtask)

    def retranslateUi(self, addtask):
        _translate = QtCore.QCoreApplication.translate
        addtask.setWindowTitle(_translate("addtask", "Dialog"))
        self.addtasktitre.setText(_translate("addtask", "Nouvelle tâche"))
        self.addtasknomuser.setPlaceholderText(_translate("addtask", "Nom"))
        self.addtaskboutoncon.setText(_translate("addtask", "Créer la tâche"))
        self.addtaskcroix.setText(_translate("addtask", "X"))
        self.addtaskpetit.setText(_translate("addtask", "-"))
        self.addtasknom.setText(_translate("addtask", "TextLabel"))
        self.addtasknom_2.setText(_translate("addtask", "TextLabel"))
        self.addtaskprio.setItemText(0, _translate("addtask", "Selectionner une prioritée"))
        self.addtaskprio.setItemText(1, _translate("addtask", "Haute"))
        self.addtaskprio.setItemText(2, _translate("addtask", "Moyenne"))
        self.addtaskprio.setItemText(3, _translate("addtask", "Basse"))
        self.addtasktime.setDisplayFormat(_translate("addtask", "yyyy/MM/dd HH:mm:ss"))
        self.addtasketiquette.setItemText(0, _translate("addtask", "Selectionner une etiquette"))
        self.addtasketiquette.setItemText(1, _translate("addtask", "Etiquette A"))
        self.addtasketiquette.setItemText(2, _translate("addtask", "Etiquette B"))
        self.addtasketiquette.setItemText(3, _translate("addtask", "Etiquette C"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Login = QtWidgets.QWidget()
        ui = Ui_addtask()
        ui.setupUi(Login)
        Login.show()
        sys.exit(app.exec_())
