# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUItestND.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(700, 900)
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setObjectName("widget")
        self.inscrfond = QtWidgets.QLabel(self.widget)
        self.inscrfond.setGeometry(QtCore.QRect(10, 0, 650, 850))
        self.inscrfond.setStyleSheet("border-image: url(:/img/img/img1.jpg);\n"
"border-radius: 20px;")
        self.inscrfond.setText("")
        self.inscrfond.setObjectName("inscrfond")
        self.inscr = QtWidgets.QLabel(self.widget)
        self.inscr.setGeometry(QtCore.QRect(160, 125, 321, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.inscr.setFont(font)
        self.inscr.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.inscr.setAlignment(QtCore.Qt.AlignCenter)
        self.inscr.setObjectName("inscr")
        self.inscrnom = QtWidgets.QLineEdit(self.widget)
        self.inscrnom.setGeometry(QtCore.QRect(125, 300, 400, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inscrnom.sizePolicy().hasHeightForWidth())
        self.inscrnom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.inscrnom.setFont(font)
        self.inscrnom.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inscrnom.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inscrnom.setAcceptDrops(True)
        self.inscrnom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inscrnom.setAutoFillBackground(False)
        self.inscrnom.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.inscrnom.setText("")
        self.inscrnom.setCursorPosition(0)
        self.inscrnom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inscrnom.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.inscrnom.setObjectName("inscrnom")
        self.inscrmdp = QtWidgets.QLineEdit(self.widget)
        self.inscrmdp.setGeometry(QtCore.QRect(120, 430, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.inscrmdp.setFont(font)
        self.inscrmdp.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.inscrmdp.setText("")
        self.inscrmdp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inscrmdp.setObjectName("inscrmdp")
        self.inscrboutoninscr = QtWidgets.QPushButton(self.widget)
        self.inscrboutoninscr.setGeometry(QtCore.QRect(200, 600, 250, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inscrboutoninscr.setFont(font)
        self.inscrboutoninscr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inscrboutoninscr.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.inscrboutoninscr.setObjectName("inscrboutoninscr")
        self.inscrconfmdp = QtWidgets.QLineEdit(self.widget)
        self.inscrconfmdp.setGeometry(QtCore.QRect(120, 510, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.inscrconfmdp.setFont(font)
        self.inscrconfmdp.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.inscrconfmdp.setText("")
        self.inscrconfmdp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inscrconfmdp.setObjectName("inscrconfmdp")
        self.inscrannule = QtWidgets.QPushButton(self.widget)
        self.inscrannule.setGeometry(QtCore.QRect(430, 790, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inscrannule.setFont(font)
        self.inscrannule.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inscrannule.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.inscrannule.setObjectName("inscrannule")
        self.inscrcroix = QtWidgets.QPushButton(self.widget)
        self.inscrcroix.setGeometry(QtCore.QRect(590, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inscrcroix.setFont(font)
        self.inscrcroix.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);")
        self.inscrcroix.setObjectName("inscrcroix")
        self.inscrreduit = QtWidgets.QPushButton(self.widget)
        self.inscrreduit.setGeometry(QtCore.QRect(540, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.inscrreduit.setFont(font)
        self.inscrreduit.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);")
        self.inscrreduit.setObjectName("inscrreduit")
        self.inscrfondnoir = QtWidgets.QLabel(self.widget)
        self.inscrfondnoir.setGeometry(QtCore.QRect(75, 225, 500, 525))
        self.inscrfondnoir.setStyleSheet("background: rgba(0,0,0, 0.33);\n"
"border-radius: 30px;")
        self.inscrfondnoir.setText("")
        self.inscrfondnoir.setObjectName("inscrfondnoir")
        self.inscrfond.raise_()
        self.inscr.raise_()
        self.inscrboutoninscr.raise_()
        self.inscrannule.raise_()
        self.inscrcroix.raise_()
        self.inscrreduit.raise_()
        self.inscrfondnoir.raise_()
        self.inscrnom.raise_()
        self.inscrmdp.raise_()
        self.inscrconfmdp.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.inscr.setText(_translate("Login", "Inscription"))
        self.inscrnom.setPlaceholderText(_translate("Login", "Nom d\'utilisateur"))
        self.inscrmdp.setPlaceholderText(_translate("Login", "Mot de passe"))
        self.inscrboutoninscr.setText(_translate("Login", "S\'inscrire"))
        self.inscrconfmdp.setPlaceholderText(_translate("Login", "Confirmer le mot de passe"))
        self.inscrannule.setText(_translate("Login", "Annuler"))
        self.inscrcroix.setText(_translate("Login", "X"))
        self.inscrreduit.setText(_translate("Login", "-"))
import GUItestND_rc
