# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\listtaches.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, qrc

class Ui_listtask(object):
    def setupUi(self, listtask):
        listtask.setObjectName("listtask")
        listtask.setEnabled(True)
        listtask.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        listtask.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        listtask.resize(700, 900)
        self.listtaskmainwidget = QtWidgets.QWidget(listtask)
        self.listtaskmainwidget.setGeometry(QtCore.QRect(25, 25, 650, 850))
        self.listtaskmainwidget.setObjectName("listtaskmainwidget")
        self.listtaskimgback = QtWidgets.QLabel(self.listtaskmainwidget)
        self.listtaskimgback.setGeometry(QtCore.QRect(0, 0, 650, 850))
        self.listtaskimgback.setStyleSheet("border-image: url(:/img/img/cover.jpg);\n"
"border-radius: 20px;")
        self.listtaskimgback.setText("")
        self.listtaskimgback.setObjectName("listtaskimgback")
        self.listtasktitre = QtWidgets.QLabel(self.listtaskmainwidget)
        self.listtasktitre.setGeometry(QtCore.QRect(125, 75, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.listtasktitre.setFont(font)
        self.listtasktitre.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listtasktitre.setAlignment(QtCore.Qt.AlignCenter)
        self.listtasktitre.setObjectName("listtasktitre")
        self.listtaskboutoncon = QtWidgets.QToolButton(self.listtaskmainwidget)
        self.listtaskboutoncon.setGeometry(QtCore.QRect(200, 750, 250, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listtaskboutoncon.setFont(font)
        self.listtaskboutoncon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listtaskboutoncon.setAutoFillBackground(False)
        self.listtaskboutoncon.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listtaskboutoncon.setCheckable(False)
        self.listtaskboutoncon.setAutoExclusive(False)
        self.listtaskboutoncon.setAutoRepeatInterval(100)
        self.listtaskboutoncon.setObjectName("listtaskboutoncon")
        self.listtaskcroix = QtWidgets.QToolButton(self.listtaskmainwidget)
        self.listtaskcroix.setGeometry(QtCore.QRect(590, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listtaskcroix.setFont(font)
        self.listtaskcroix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listtaskcroix.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.listtaskcroix.setObjectName("listtaskcroix")
        self.listtaskpetit = QtWidgets.QToolButton(self.listtaskmainwidget)
        self.listtaskpetit.setGeometry(QtCore.QRect(540, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.listtaskpetit.setFont(font)
        self.listtaskpetit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listtaskpetit.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.listtaskpetit.setObjectName("listtaskpetit")
        self.listtaskwidgscroll = QtWidgets.QWidget(self.listtaskmainwidget)
        self.listtaskwidgscroll.setGeometry(QtCore.QRect(50, 290, 550, 450))
        self.listtaskwidgscroll.setObjectName("listtaskwidgscroll")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.listtaskwidgscroll)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listtaskcrollArea = QtWidgets.QScrollArea(self.listtaskwidgscroll)
        self.listtaskcrollArea.setStyleSheet("background: rgb(255, 255, 255, 0;);\n"
"border-radius: 0px;")
        self.listtaskcrollArea.setWidgetResizable(True)
        self.listtaskcrollArea.setObjectName("listtaskcrollArea")
        self.alisttaskscrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.alisttaskscrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 513, 480))
        self.alisttaskscrollAreaWidgetContents_2.setObjectName("alisttaskscrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.alisttaskscrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listtasktache = QtWidgets.QWidget(self.alisttaskscrollAreaWidgetContents_2)
        self.listtasktache.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listtasktache.setObjectName("listtasktache")
        self.listtasknomtache = QtWidgets.QLineEdit(self.listtasktache)
        self.listtasknomtache.setGeometry(QtCore.QRect(10, 10, 200, 40))
        self.listtasknomtache.setStyleSheet("font-size: 16px;")
        self.listtasknomtache.setObjectName("listtasknomtache")
        self.listtaskdescriptiontache = QtWidgets.QTextEdit(self.listtasktache)
        self.listtaskdescriptiontache.setGeometry(QtCore.QRect(10, 60, 200, 80))
        self.listtaskdescriptiontache.setObjectName("listtaskdescriptiontache")
        self.listtaskassigne_a = QtWidgets.QLabel(self.listtasktache)
        self.listtaskassigne_a.setGeometry(QtCore.QRect(220, 10, 80, 40))
        self.listtaskassigne_a.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskassigne_a.setObjectName("listtaskassigne_a")
        self.listtasknompersonne = QtWidgets.QLabel(self.listtasktache)
        self.listtasknompersonne.setGeometry(QtCore.QRect(300, 12, 125, 41))
        self.listtasknompersonne.setStyleSheet("font-size: 14px;")
        self.listtasknompersonne.setAlignment(QtCore.Qt.AlignCenter)
        self.listtasknompersonne.setObjectName("listtasknompersonne")
        self.listtaskdatedefin = QtWidgets.QLabel(self.listtasktache)
        self.listtaskdatedefin.setGeometry(QtCore.QRect(220, 80, 80, 40))
        self.listtaskdatedefin.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskdatedefin.setObjectName("listtaskdatedefin")
        self.listtaskdatefintache = QtWidgets.QLabel(self.listtasktache)
        self.listtaskdatefintache.setGeometry(QtCore.QRect(300, 60, 125, 81))
        self.listtaskdatefintache.setStyleSheet("font-size: 14px;")
        self.listtaskdatefintache.setAlignment(QtCore.Qt.AlignCenter)
        self.listtaskdatefintache.setObjectName("listtaskdatefintache")
        self.listtaskcheckBox = QtWidgets.QCheckBox(self.listtasktache)
        self.listtaskcheckBox.setGeometry(QtCore.QRect(450, 60, 31, 31))
        self.listtaskcheckBox.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskcheckBox.setText("")
        self.listtaskcheckBox.setObjectName("listtaskcheckBox")
        self.gridLayout_2.addWidget(self.listtasktache, 0, 0, 1, 1)
        self.listtasktache_2 = QtWidgets.QWidget(self.alisttaskscrollAreaWidgetContents_2)
        self.listtasktache_2.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listtasktache_2.setObjectName("listtasktache_2")
        self.listtasknomtache_2 = QtWidgets.QLineEdit(self.listtasktache_2)
        self.listtasknomtache_2.setGeometry(QtCore.QRect(10, 10, 200, 40))
        self.listtasknomtache_2.setStyleSheet("font-size: 16px;")
        self.listtasknomtache_2.setObjectName("listtasknomtache_2")
        self.listtaskdescriptiontache_2 = QtWidgets.QTextEdit(self.listtasktache_2)
        self.listtaskdescriptiontache_2.setGeometry(QtCore.QRect(10, 60, 200, 80))
        self.listtaskdescriptiontache_2.setObjectName("listtaskdescriptiontache_2")
        self.listtaskassigne_a_2 = QtWidgets.QLabel(self.listtasktache_2)
        self.listtaskassigne_a_2.setGeometry(QtCore.QRect(220, 10, 80, 40))
        self.listtaskassigne_a_2.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskassigne_a_2.setObjectName("listtaskassigne_a_2")
        self.listtasknompersonne_2 = QtWidgets.QLabel(self.listtasktache_2)
        self.listtasknompersonne_2.setGeometry(QtCore.QRect(300, 12, 125, 41))
        self.listtasknompersonne_2.setStyleSheet("font-size: 14px;")
        self.listtasknompersonne_2.setAlignment(QtCore.Qt.AlignCenter)
        self.listtasknompersonne_2.setObjectName("listtasknompersonne_2")
        self.listtaskdatedefin_2 = QtWidgets.QLabel(self.listtasktache_2)
        self.listtaskdatedefin_2.setGeometry(QtCore.QRect(220, 80, 80, 40))
        self.listtaskdatedefin_2.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskdatedefin_2.setObjectName("listtaskdatedefin_2")
        self.listtaskdatefintache_2 = QtWidgets.QLabel(self.listtasktache_2)
        self.listtaskdatefintache_2.setGeometry(QtCore.QRect(300, 60, 125, 81))
        self.listtaskdatefintache_2.setStyleSheet("font-size: 14px;")
        self.listtaskdatefintache_2.setAlignment(QtCore.Qt.AlignCenter)
        self.listtaskdatefintache_2.setObjectName("listtaskdatefintache_2")
        self.listtaskcheckBox_2 = QtWidgets.QCheckBox(self.listtasktache_2)
        self.listtaskcheckBox_2.setGeometry(QtCore.QRect(450, 60, 31, 31))
        self.listtaskcheckBox_2.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskcheckBox_2.setText("")
        self.listtaskcheckBox_2.setObjectName("listtaskcheckBox_2")
        self.gridLayout_2.addWidget(self.listtasktache_2, 1, 0, 1, 1)
        self.listtasktache_3 = QtWidgets.QWidget(self.alisttaskscrollAreaWidgetContents_2)
        self.listtasktache_3.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.listtasktache_3.setObjectName("listtasktache_3")
        self.listtasknomtache_3 = QtWidgets.QLineEdit(self.listtasktache_3)
        self.listtasknomtache_3.setGeometry(QtCore.QRect(10, 10, 200, 40))
        self.listtasknomtache_3.setStyleSheet("font-size: 16px;")
        self.listtasknomtache_3.setObjectName("listtasknomtache_3")
        self.listtaskdescriptiontache_3 = QtWidgets.QTextEdit(self.listtasktache_3)
        self.listtaskdescriptiontache_3.setGeometry(QtCore.QRect(10, 60, 200, 80))
        self.listtaskdescriptiontache_3.setObjectName("listtaskdescriptiontache_3")
        self.listtaskassigne_a_3 = QtWidgets.QLabel(self.listtasktache_3)
        self.listtaskassigne_a_3.setGeometry(QtCore.QRect(220, 10, 80, 40))
        self.listtaskassigne_a_3.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskassigne_a_3.setObjectName("listtaskassigne_a_3")
        self.listtasknompersonne_3 = QtWidgets.QLabel(self.listtasktache_3)
        self.listtasknompersonne_3.setGeometry(QtCore.QRect(300, 12, 125, 41))
        self.listtasknompersonne_3.setStyleSheet("font-size: 14px;")
        self.listtasknompersonne_3.setAlignment(QtCore.Qt.AlignCenter)
        self.listtasknompersonne_3.setObjectName("listtasknompersonne_3")
        self.listtaskdatedefin_3 = QtWidgets.QLabel(self.listtasktache_3)
        self.listtaskdatedefin_3.setGeometry(QtCore.QRect(220, 80, 80, 40))
        self.listtaskdatedefin_3.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskdatedefin_3.setObjectName("listtaskdatedefin_3")
        self.listtaskdatefintache_3 = QtWidgets.QLabel(self.listtasktache_3)
        self.listtaskdatefintache_3.setGeometry(QtCore.QRect(300, 60, 125, 81))
        self.listtaskdatefintache_3.setStyleSheet("font-size: 14px;")
        self.listtaskdatefintache_3.setAlignment(QtCore.Qt.AlignCenter)
        self.listtaskdatefintache_3.setObjectName("listtaskdatefintache_3")
        self.listtaskcheckBox_3 = QtWidgets.QCheckBox(self.listtasktache_3)
        self.listtaskcheckBox_3.setGeometry(QtCore.QRect(450, 60, 31, 31))
        self.listtaskcheckBox_3.setStyleSheet("background: rgba(255, 255, 255, .0);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;")
        self.listtaskcheckBox_3.setText("")
        self.listtaskcheckBox_3.setObjectName("listtaskcheckBox_3")
        self.gridLayout_2.addWidget(self.listtasktache_3, 2, 0, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 150)
        self.gridLayout_2.setRowMinimumHeight(1, 150)
        self.gridLayout_2.setRowMinimumHeight(2, 150)
        self.listtaskcrollArea.setWidget(self.alisttaskscrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.listtaskcrollArea)
        self.listtaskchampdescription = QtWidgets.QTextBrowser(self.listtaskmainwidget)
        self.listtaskchampdescription.setGeometry(QtCore.QRect(50, 200, 550, 75))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.listtaskchampdescription.setFont(font)
        self.listtaskchampdescription.setStyleSheet("font-size: 16px;\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.listtaskchampdescription.setObjectName("listtaskchampdescription")
        self.listtaskdescriptionlabel = QtWidgets.QLabel(self.listtaskmainwidget)
        self.listtaskdescriptionlabel.setGeometry(QtCore.QRect(50, 175, 550, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listtaskdescriptionlabel.setFont(font)
        self.listtaskdescriptionlabel.setStyleSheet("color: rgba(255, 255, 255, .80;);")
        self.listtaskdescriptionlabel.setObjectName("listtaskdescriptionlabel")
        self.listtaskimgback.raise_()
        self.listtasktitre.raise_()
        self.listtaskcroix.raise_()
        self.listtaskpetit.raise_()
        self.listtaskboutoncon.raise_()
        self.listtaskwidgscroll.raise_()
        self.listtaskchampdescription.raise_()
        self.listtaskdescriptionlabel.raise_()

        self.retranslateUi(listtask)
        QtCore.QMetaObject.connectSlotsByName(listtask)

    def retranslateUi(self, listtask):
        _translate = QtCore.QCoreApplication.translate
        listtask.setWindowTitle(_translate("listtask", "Dialog"))
        self.listtasktitre.setText(_translate("listtask", "Nom de la ToDoList"))
        self.listtaskboutoncon.setText(_translate("listtask", "Créer la tâche"))
        self.listtaskcroix.setText(_translate("listtask", "X"))
        self.listtaskpetit.setText(_translate("listtask", "-"))
        self.listtasknomtache.setText(_translate("listtask", "Nom"))
        self.listtaskdescriptiontache.setHtml(_translate("listtask", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Description</p></body></html>"))
        self.listtaskassigne_a.setText(_translate("listtask", "Assignée à :"))
        self.listtasknompersonne.setText(_translate("listtask", "Daniel DEMIRBAG"))
        self.listtaskdatedefin.setText(_translate("listtask", "Date de fin :"))
        self.listtaskdatefintache.setText(_translate("listtask", "12/12/2023"))
        self.listtasknomtache_2.setText(_translate("listtask", "Nom"))
        self.listtaskdescriptiontache_2.setHtml(_translate("listtask", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Description</p></body></html>"))
        self.listtaskassigne_a_2.setText(_translate("listtask", "Assignée à :"))
        self.listtasknompersonne_2.setText(_translate("listtask", "Daniel DEMIRBAG"))
        self.listtaskdatedefin_2.setText(_translate("listtask", "Date de fin :"))
        self.listtaskdatefintache_2.setText(_translate("listtask", "12/12/2023"))
        self.listtasknomtache_3.setText(_translate("listtask", "Nom"))
        self.listtaskdescriptiontache_3.setHtml(_translate("listtask", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Description</p></body></html>"))
        self.listtaskassigne_a_3.setText(_translate("listtask", "Assignée à :"))
        self.listtasknompersonne_3.setText(_translate("listtask", "Daniel DEMIRBAG"))
        self.listtaskdatedefin_3.setText(_translate("listtask", "Date de fin :"))
        self.listtaskdatefintache_3.setText(_translate("listtask", "12/12/2023"))
        self.listtaskchampdescription.setHtml(_translate("listtask", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">description</span></p></body></html>"))
        self.listtaskdescriptionlabel.setText(_translate("listtask", "Description :"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Login = QtWidgets.QWidget()
        ui = Ui_listtask()
        ui.setupUi(Login)
        Login.show()
        sys.exit(app.exec_())
