# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUItestDaniel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, qrc


class Ui_addtodolist(object):
    def setupUi(self, addtodolist):
        addtodolist.setObjectName("addtodolist")
        addtodolist.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        addtodolist.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        addtodolist.setEnabled(True)
        addtodolist.resize(700, 900)
        self.widget = QtWidgets.QWidget(addtodolist)
        self.widget.setGeometry(QtCore.QRect(25, 25, 650, 850))
        self.widget.setObjectName("widget")
        self.addtodoimgback = QtWidgets.QLabel(self.widget)
        self.addtodoimgback.setGeometry(QtCore.QRect(0, 0, 650, 850))
        self.addtodoimgback.setStyleSheet("border-image: url(:/img/img/cover.jpg);\n"
"border-radius: 20px;")
        self.addtodoimgback.setText("")
        self.addtodoimgback.setObjectName("addtodoimgback")
        self.addtodotitre = QtWidgets.QLabel(self.widget)
        self.addtodotitre.setGeometry(QtCore.QRect(125, 75, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.addtodotitre.setFont(font)
        self.addtodotitre.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.addtodotitre.setAlignment(QtCore.Qt.AlignCenter)
        self.addtodotitre.setObjectName("addtodotitre")
        self.addtodonomuser = QtWidgets.QLineEdit(self.widget)
        self.addtodonomuser.setGeometry(QtCore.QRect(75, 200, 500, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addtodonomuser.sizePolicy().hasHeightForWidth())
        self.addtodonomuser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.addtodonomuser.setFont(font)
        self.addtodonomuser.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.addtodonomuser.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.addtodonomuser.setAcceptDrops(True)
        self.addtodonomuser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addtodonomuser.setAutoFillBackground(False)
        self.addtodonomuser.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.addtodonomuser.setText("")
        self.addtodonomuser.setCursorPosition(0)
        self.addtodonomuser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.addtodonomuser.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.addtodonomuser.setObjectName("addtodonomuser")
        self.addtodomdp = QtWidgets.QLineEdit(self.widget)
        self.addtodomdp.setGeometry(QtCore.QRect(75, 275, 500, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.addtodomdp.setFont(font)
        self.addtodomdp.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.addtodomdp.setText("")
        self.addtodomdp.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.addtodomdp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.addtodomdp.setObjectName("addtodomdp")
        self.addtodoboutoncon = QtWidgets.QToolButton(self.widget)
        self.addtodoboutoncon.setGeometry(QtCore.QRect(200, 675, 250, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addtodoboutoncon.setFont(font)
        self.addtodoboutoncon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addtodoboutoncon.setAutoFillBackground(False)
        self.addtodoboutoncon.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.addtodoboutoncon.setCheckable(False)
        self.addtodoboutoncon.setAutoExclusive(False)
        self.addtodoboutoncon.setAutoRepeatInterval(100)
        self.addtodoboutoncon.setObjectName("addtodoboutoncon")
        self.addtodocroix = QtWidgets.QToolButton(self.widget)
        self.addtodocroix.setGeometry(QtCore.QRect(590, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addtodocroix.setFont(font)
        self.addtodocroix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addtodocroix.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.addtodocroix.setObjectName("addtodocroix")
        self.addtodopetit = QtWidgets.QToolButton(self.widget)
        self.addtodopetit.setGeometry(QtCore.QRect(540, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.addtodopetit.setFont(font)
        self.addtodopetit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addtodopetit.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.addtodopetit.setObjectName("addtodopetit")
        self.addtodofondnoir = QtWidgets.QLabel(self.widget)
        self.addtodofondnoir.setGeometry(QtCore.QRect(25, 175, 600, 450))
        self.addtodofondnoir.setStyleSheet("background: rgba(0, 0, 0, .33);\n"
"border-radius: 30px;")
        self.addtodofondnoir.setText("")
        self.addtodofondnoir.setObjectName("addtodofondnoir")
        self.addtodowidgscroll = QtWidgets.QWidget(self.widget)
        self.addtodowidgscroll.setGeometry(QtCore.QRect(60, 400, 525, 200))
        self.addtodowidgscroll.setObjectName("addtodowidgscroll")
        self.gridLayout = QtWidgets.QGridLayout(self.addtodowidgscroll)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.addtodoscrollArea = QtWidgets.QScrollArea(self.addtodowidgscroll)
        self.addtodoscrollArea.setStyleSheet("background: rgb(255, 255, 255, 0;);\n"
"border-radius: 0px;")
        self.addtodoscrollArea.setWidgetResizable(True)
        self.addtodoscrollArea.setObjectName("addtodoscrollArea")
        self.addtodoscrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.addtodoscrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 505, 180))
        self.addtodoscrollAreaWidgetContents_2.setObjectName("addtodoscrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.addtodoscrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addtodocheckBox = QtWidgets.QCheckBox(self.addtodoscrollAreaWidgetContents_2)
        self.addtodocheckBox.setStyleSheet(" height: 32px;")
        self.addtodocheckBox.setText("")
        self.addtodocheckBox.setObjectName("addtodocheckBox")
        self.gridLayout_2.addWidget(self.addtodocheckBox, 4, 0, 1, 1)
        self.addtodonom = QtWidgets.QLabel(self.addtodoscrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addtodonom.setFont(font)
        self.addtodonom.setStyleSheet("color: rgba(255, 255, 255, .60;);")
        self.addtodonom.setObjectName("addtodonom")
        self.gridLayout_2.addWidget(self.addtodonom, 4, 1, 1, 1)
        self.addtodocheckBox_2 = QtWidgets.QCheckBox(self.addtodoscrollAreaWidgetContents_2)
        self.addtodocheckBox_2.setStyleSheet(" height: 32px;")
        self.addtodocheckBox_2.setText("")
        self.addtodocheckBox_2.setIconSize(QtCore.QSize(16, 16))
        self.addtodocheckBox_2.setObjectName("addtodocheckBox_2")
        self.gridLayout_2.addWidget(self.addtodocheckBox_2, 3, 0, 1, 1)
        self.addtodonom_2 = QtWidgets.QLabel(self.addtodoscrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addtodonom_2.setFont(font)
        self.addtodonom_2.setStyleSheet("color: rgba(255, 255, 255, .60;);")
        self.addtodonom_2.setObjectName("addtodonom_2")
        self.gridLayout_2.addWidget(self.addtodonom_2, 3, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.addtodoscrollArea.setWidget(self.addtodoscrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.addtodoscrollArea, 0, 0, 1, 1)
        self.addtodoimgback.raise_()
        self.addtodotitre.raise_()
        self.addtodocroix.raise_()
        self.addtodopetit.raise_()
        self.addtodoboutoncon.raise_()
        self.addtodofondnoir.raise_()
        self.addtodonomuser.raise_()
        self.addtodomdp.raise_()
        self.addtodowidgscroll.raise_()

        self.retranslateUi(addtodolist)
        QtCore.QMetaObject.connectSlotsByName(addtodolist)

    def retranslateUi(self, addtodolist):
        _translate = QtCore.QCoreApplication.translate
        addtodolist.setWindowTitle(_translate("addtodolist", "Dialog"))
        self.addtodotitre.setText(_translate("addtodolist", "Nouvelle ToDoList"))
        self.addtodonomuser.setPlaceholderText(_translate("addtodolist", "Nom"))
        self.addtodomdp.setPlaceholderText(_translate("addtodolist", "Description"))
        self.addtodoboutoncon.setText(_translate("addtodolist", "Créer la ToDoList"))
        self.addtodocroix.setText(_translate("addtodolist", "X"))
        self.addtodopetit.setText(_translate("addtodolist", "-"))
        self.addtodonom.setText(_translate("addtodolist", "TextLabel"))
        self.addtodonom_2.setText(_translate("addtodolist", "TextLabel"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Login = QtWidgets.QWidget()
        ui = Ui_addtodolist()
        ui.setupUi(Login)
        Login.show()
        sys.exit(app.exec_())
