# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resetpwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, qrc


class Ui_reset(object):
    def setupUi(self, reset):
        reset.setObjectName("reset")
        reset.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        reset.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        reset.setEnabled(True)
        reset.resize(700, 900)
        self.widget = QtWidgets.QWidget(reset)
        self.widget.setGeometry(QtCore.QRect(25, 25, 650, 850))
        self.widget.setObjectName("widget")
        self.resetimgback = QtWidgets.QLabel(self.widget)
        self.resetimgback.setGeometry(QtCore.QRect(0, 0, 650, 850))
        self.resetimgback.setStyleSheet("border-image: url(:/img/img/cover.jpg);\n"
"border-radius: 20px;")
        self.resetimgback.setText("")
        self.resetimgback.setObjectName("resetimgback")
        self.resettitre = QtWidgets.QLabel(self.widget)
        self.resettitre.setGeometry(QtCore.QRect(30, 125, 591, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.resettitre.setFont(font)
        self.resettitre.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.resettitre.setAlignment(QtCore.Qt.AlignCenter)
        self.resettitre.setObjectName("resettitre")
        self.resetmail = QtWidgets.QLineEdit(self.widget)
        self.resetmail.setGeometry(QtCore.QRect(125, 300, 400, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetmail.sizePolicy().hasHeightForWidth())
        self.resetmail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.resetmail.setFont(font)
        self.resetmail.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.resetmail.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.resetmail.setAcceptDrops(True)
        self.resetmail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resetmail.setAutoFillBackground(False)
        self.resetmail.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.resetmail.setText("")
        self.resetmail.setCursorPosition(0)
        self.resetmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.resetmail.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.resetmail.setObjectName("resetmail")
        self.resetuser = QtWidgets.QLineEdit(self.widget)
        self.resetuser.setGeometry(QtCore.QRect(125, 400, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.resetuser.setFont(font)
        self.resetuser.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"background: rgba(255, 255, 255, 0);")
        self.resetuser.setText("")
        self.resetuser.setEchoMode(QtWidgets.QLineEdit.Password)
        self.resetuser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.resetuser.setObjectName("resetuser")
        self.resetboutonreset = QtWidgets.QToolButton(self.widget)
        self.resetboutonreset.setGeometry(QtCore.QRect(200, 550, 250, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resetboutonreset.setFont(font)
        self.resetboutonreset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetboutonreset.setAutoFillBackground(False)
        self.resetboutonreset.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.resetboutonreset.setCheckable(False)
        self.resetboutonreset.setAutoExclusive(False)
        self.resetboutonreset.setAutoRepeatInterval(100)
        self.resetboutonreset.setObjectName("resetboutonreset")
        self.resetcroix = QtWidgets.QToolButton(self.widget)
        self.resetcroix.setGeometry(QtCore.QRect(590, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resetcroix.setFont(font)
        self.resetcroix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetcroix.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.resetcroix.setObjectName("resetcroix")
        self.resetpetit = QtWidgets.QToolButton(self.widget)
        self.resetpetit.setGeometry(QtCore.QRect(540, 20, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.resetpetit.setFont(font)
        self.resetpetit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetpetit.setStyleSheet("border:none;\n"
"background: rgba(255, 255, 255, 0);\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, .75);")
        self.resetpetit.setObjectName("resetpetit")
        self.resetfondnoir = QtWidgets.QLabel(self.widget)
        self.resetfondnoir.setGeometry(QtCore.QRect(75, 225, 500, 525))
        self.resetfondnoir.setStyleSheet("background: rgba(0, 0, 0, .33);\n"
"border-radius: 30px;")
        self.resetfondnoir.setText("")
        self.resetfondnoir.setObjectName("resetfondnoir")
        self.resetboutonannule = QtWidgets.QToolButton(self.widget)
        self.resetboutonannule.setGeometry(QtCore.QRect(475, 775, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resetboutonannule.setFont(font)
        self.resetboutonannule.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetboutonannule.setAutoFillBackground(False)
        self.resetboutonannule.setStyleSheet("background: rgba(255, 255, 255, .5);\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.resetboutonannule.setCheckable(False)
        self.resetboutonannule.setAutoExclusive(False)
        self.resetboutonannule.setAutoRepeatInterval(100)
        self.resetboutonannule.setObjectName("resetboutonannule")
        self.resetimgback.raise_()
        self.resettitre.raise_()
        self.resetcroix.raise_()
        self.resetpetit.raise_()
        self.resetfondnoir.raise_()
        self.resetboutonreset.raise_()
        self.resetuser.raise_()
        self.resetmail.raise_()
        self.resetboutonannule.raise_()

        self.retranslateUi(reset)
        QtCore.QMetaObject.connectSlotsByName(reset)

    def retranslateUi(self, reset):
        _translate = QtCore.QCoreApplication.translate
        reset.setWindowTitle(_translate("reset", "Dialog"))
        self.resettitre.setText(_translate("reset", "Réinitialiser mot de passe"))
        self.resetmail.setPlaceholderText(_translate("reset", "Email"))
        self.resetuser.setPlaceholderText(_translate("reset", "Utilisateur"))
        self.resetboutonreset.setText(_translate("reset", "Réinitialiser"))
        self.resetcroix.setText(_translate("reset", "X"))
        self.resetpetit.setText(_translate("reset", "-"))
        self.resetboutonannule.setText(_translate("reset", "Annuler"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Login = QtWidgets.QWidget()
        ui = Ui_reset()
        ui.setupUi(Login)
        Login.show()
        sys.exit(app.exec_())
